### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by haas-daniel** [leitwerk-de/lssh#3]
Lssh throws the following errors in a python3.12 environment:

/usr/local/lib/lssh/hostlist.py:40: SyntaxWarning: invalid escape sequence '\s'
  m = re.match('^\s*Host\s+([\S]+)\s*$', line, re.IGNORECASE)
/usr/local/lib/lssh/hostlist.py:48: SyntaxWarning: invalid escape sequence '\s'
  m = re.match('^\s*proxyjump\s+([\S]+)\s*$', line, re.IGNORECASE)
/usr/local/lib/lssh/hostlist.py:51: SyntaxWarning: invalid escape sequence '\s'
  m = re.match('^\s*#\s*lssh:(file)?keywords\s(.*)$', line, re.IGNORECASE)
/usr/local/lib/lssh/hostlist.py:61: SyntaxWarning: invalid escape sequence '\s'
  m = re.match('^\s*#\s*lssh:displayname\s+(\S.*)$', line, re.IGNORECASE)
/usr/local/lib/lssh/hostlist.py:64: SyntaxWarning: invalid escape sequence '\s'
  m = re.match('^\s*#\s*lssh:assignedcustomer\s+(\S.*)$', line, re.IGNORECASE)
/usr/local/lib/lssh/config_validation.py:264: SyntaxWarning: invalid escape sequence '\S'
  m = re.match('^(\\s*)([a-zA-Z]+)(\\s+)(\S.*)$', line)

**Comment by leitwerk-ag** [comment]
thx for your report! :)
can you please test https://github.com/leitwerk-ag/lssh/tree/dev-fix-3 ?

**Comment by haas-daniel** [comment]
This works. thx :)
