### ISSUE TITLE
debian-user-install replaces .bashrc content

### ISSUE THREAD

**Issue by haas-daniel** [leitwerk-de/lssh#4]
content of .bashrc is replaced by debian-user-install:
https://github.com/leitwerk-ag/lssh/blob/d70458d3e28796dcaf7eb5e85bdf09e952727ae5/install/debian-user-install#L151C1-L151C36

content should be appended (use "a" instad of "w")

**Comment by leitwerk-ag** [comment]
thx @haas-daniel ! :)
